In [9]:
import tensorflow as tf
import numpy as np

In [10]:
ones = tf.ones(shape=[2, 3])
ones

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [11]:
x = np.random.randint(0, 10, size=[2, 3])

In [12]:
x

array([[3, 2, 5],
       [9, 7, 0]])

In [13]:
x.ndim

2

In [14]:
y = np.random.randint(0, 10, size=[2, 3])
y

array([[0, 9, 6],
       [7, 9, 6]])

In [16]:
y @ x

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [17]:
y @ np.transpose(x)

array([[ 48,  63],
       [ 69, 126]])

In [18]:
tf.__version__

'2.16.1'

In [21]:
import time

start = time.time()

np.random.randint(0, 100000, size=[100000, 10000]) 

print(time.time() - start)

23.228147983551025
