# Introduction to Tensors with Tensorflow

Helloo everyone, It's been a very long time since I've made any articles and I've been kinda missing the fun of writing articles. So, I'm back with another article series. This article series will be about `Neural Networks` and `TensorFlow`. AS always I'm `Md. Rishat Talukder AKA Itvaya`. let's get this thing started.

- [LinkedIn](https://www.linkedin.com/in/pro-programmer/)
- [YouTube](http://www.youtube.com/@itvaya)
- [gtihub](https://github.com/RishatTalukder/Deep_Learning_With_Tensorflow)
- [Gmail](talukderrishat2@gmail.com)
- [discord](https://discord.gg/ZB495XggcF)

**prerequisite**:

- **Basic understanding of numpy and pandas.**
- **Optional: Overall basic understanding of machine learning.**

# Introduction to Tensorflow

What is `TensorFlow`?

`TensorFlow` is an open-source machine learning library for research and production. TensorFlow offers APIs for beginners and experts to develop for desktop, mobile, web, and cloud. See the sections below to get started.

> I like to think of tensorflow as a more powerful version of `numpy`. If you know numpy your work is already 60% done.

In this article we will see how to get started with `TensorFlow` and what are `tensors` ?

## Installation

```bash
python3 -m pip install 'tensorflow[and-cuda]'
```

If you have a Nvidia GPU this should works amazing... And if you don't have a gpu there should be no issue there too.

In [1]:
import warnings

warnings.filterwarnings("ignore")

In [2]:
import tensorflow as tf
print(tf.__version__)

2026-04-26 16:48:05.999583: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


2.20.0


There you go we have `imported tensorflow` and printed the version of the `tensorflow` library.
I'm using `TensorFlow 2.16.1` in this notebook.

## Tensors

A `tensor` is a `generalization` of vectors and matrices to potentially higher dimensions. Internally, TensorFlow represents tensors as n-dimensional arrays of base datatypes.

there many ways to create `tensors` in `tensorflow` but most common ways are using `tf.constant` and `tf.Variable` functions.

## tf.constant

Here is how you can create a `tensor` using `tf.constant` function


In [3]:
scaler = tf.constant(1)
scaler

I0000 00:00:1777200510.331230  387550 gpu_device.cc:2020] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 9702 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3060, pci bus id: 0000:05:00.0, compute capability: 8.6


<tf.Tensor: shape=(), dtype=int32, numpy=1>

here, we have created a `tensor` that contains a numpy value `1` and the datatype of the tensor is `int32`.

if you take a closer look you can see that the shape of the tensor is `()` which means it is a `0-D` tensor. So, it's a scalar.

We have a tensor in our hand.

Now you might think why does I named the tensor as `scaler` because it's a `0-D` tensor AKA a `scaler`.

> A `scaler` value is something that has only magnitude and no direction.

To prove it we can see the dimension of the tensor.

In [4]:
scaler.ndim

0

Here you go. You can just use the `variable_name.ndim` to get the dimension of the tensor.

Now, let's see how to create a `1-D` tensor.

In [5]:
vector = tf.constant([1, 2, 3])

vector

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

And we have created a `1-D` tensor. We just pass a `list` of values or a `numpy array` to the `tf.constant` function.

And you can see that the tensor is containing a `numpy array` of values `[1, 2, 3]` and the datatype of the tensor is `int32` and the shape of the tensor is `(3,)` which means it is a `1-D` tensor.

Now we can see the dimansions.

In [6]:
vector.ndim

1

and you see that the tensor is a `1-D` tensor.

> A `vector` is a 1-D array of values.

And we can keep going. So let's try top make a `2-D` tensor and also a `3-D` tensor.

In [7]:
matrix = tf.constant([
    [1, 2],
    [3, 4]
])

In [8]:
matrix.ndim

2

AAAND we made a `2-D` tensor. We just passed a `list of lists` to the `tf.constant` function. Now we see the shape of the tensor.

In [9]:
matrix.shape

TensorShape([2, 2])

it's a 2 by 2 tensor. Simply it's a `2-D` array of values is refered to as a `matrix`.

In [10]:
n_dimantional_matrix = tf.constant([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
])

In [11]:
n_dimantional_matrix

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)>

Ther you go, we have created a `3-D` tensor. We just passed a `list of lists of lists` to the `tf.constant` function. Now we see the shape of the tensor.

So, we have created `scaler`, `vector`, `matrix`, and `3-D` or anything greater then that is called a `tensor` in general.

> 0-d array is called a `scaler`. 1-d array is called a `vector`. 2-d array is called a `matrix`. n-d array is called a `tensor`.

Now let's see how to create a `tensor` using the `tf.Variable` function.

`tf.constant` has many more methods and attributes that we can use and also we can pass different arguments to set the data type of the tensor, shape of the tensor, etc.

In [12]:
tf.constant([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]], dtype=tf.float16)

<tf.Tensor: shape=(2, 2, 3), dtype=float16, numpy=
array([[[ 1.,  2.,  3.],
        [ 4.,  5.,  6.]],

       [[ 7.,  8.,  9.],
        [10., 11., 12.]]], dtype=float16)>

YOu should check out the official documentations for [constant](https://www.tensorflow.org/api_docs/python/tf/constant)

Although `tf.constant` is great for creating a `tensor` but it's not the only way and this constant tensor is immutable. Once you create a constant tensor you can't change the values of the tensor.

In [13]:
vector = tf.constant([1,2,3,4,5])

In [14]:
vector[1] = 3
vector

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

As you can see that you cannot assign a to a index of the vector. It's immutable.

## tf.Variable

So, if you want to create a mutable tensor you can use the `tf.Variable` function.

This is a more powerful version of the `tf.constant` function.

Useing `tf.Variable` function we can do everything that we can do with `tf.constant` function and many more.

In [15]:
vector = tf.Variable([1,2,3,4,5])
vector

<tf.Variable 'Variable:0' shape=(5,) dtype=int32, numpy=array([1, 2, 3, 4, 5], dtype=int32)>

In [16]:
vector.dtype

tf.int32

In [17]:
vector.shape

TensorShape([5])

Now, let's try to assign a value to a index of the vector.

In [18]:
vector[1] = 3

TypeError: 'ResourceVariable' object does not support item assignment

Annnnd this doesn't work. In tensorflow, assignment doesn't work like normal assignment. You can't use the assignment operator `=` to assign a value to a index of the vector, instead you have to use the `assign` method.

In [19]:
vector[1].assign(32)
vector

<tf.Variable 'Variable:0' shape=(5,) dtype=int32, numpy=array([ 1, 32,  3,  4,  5], dtype=int32)>

Assignment is working now. Now, before we move to more wierd things I want to talk about the output of the `tf.Variable` function.

> `<tf.Variable 'Variable:0' shape=(5,) dtype=int32, numpy=array([ 1, 32,  3,  4,  5], dtype=int32)>`

- The first part is the type of tensor `tf.Variable`.
- `Variable:0` means that the variable is the zeroth variable. Tensorflow assigns unique names to tensor which is made with `tf.Variable` function.
- `shape=(5,)` means that the shape of the tensor is 5.
- `dtype=int32` means that the data type of the tensor is `int32`.
- `numpy=array([ 1, 32,  3,  4,  5], dtype=int32)` means that the values of the tensor are `[ 1, 32,  3,  4,  5]` and the data type of the values is `int32`.

Now if you go to the [official documentations](https://www.tensorflow.org/api_docs/python/tf/Variable) you can see that there are a lot a of arguments that you can pass to the `tf.Variable` function and also a lot of methods and attributes that you can use when you are working with the `tf.Variable` function.

You have access to methods like:

- `assign` to assign a value to a index of the vector.
- `assign_add` to add a value to a index of the vector.
- `assign_sub` to subtract a value from a index of the vector.


## Random Tensors

As I said earlier, tensorflow is a powerful and feature rich version of numpy. It can also help us generate random tensors more easily.

In [20]:
random_1 = tf.random.Generator.from_seed(42)
random_1.normal(shape=(3, 2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193765, -1.8107855 ]], dtype=float32)>

To generate random numbers we can use the `tf.random.Generator` class and start the random number generator with the `from_seed` method.

This will return a `Generator` object that we can use to generate random numbers.

> The generator object is like a random number generator with different methods and attributes that we can use to generate random numbers from different distributions like the above I'm using the `normal` method to generate random numbers from a normal distribution with the shape of `(3, 2)`. Meaning this should generate 3 rows and 2 columns of random numbers.

> from_seed method takes a `seed` argument which is an integer.

If you don't know that the seed value does here's a short explanation.

We are generating random numbers but these are not pure random values, these and `pseudo random numbers`. Meaning each random number that this generated is dependent on the `seed` value that we pass to the `from_seed` method.

Seed define the random order of the random numbers that are generated.

So, if we set the seed, the same random number will keep being generated. If we don't then the random order will keep on changing and we will get different random numbers each time we run a file.

It is a best practice to set the seed value to a fixed value so that the random numbers are always the same during production because if the number keeps on changing any bug will be very hard to reproduce.

> Again, if you haven't learned numpy or worked with numpy you should learn numpy now, because almost everything that you are doing with tensorflow is based on numpy.

## Shuffling the data

In the process of training a machine learning model or a neural network the `order of data matters a lot`. A model can easily get overfitted(`learning a pettern so good that learning other patterns becomes tough`) so, shuffling the data before training is a must.

To shuffle the data we can use the `tf.random.shuffle` function.

In [23]:
data = random_1.normal(shape=(5, 3))
data

<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
array([[-1.7790617 ,  0.20539697, -0.22468199],
       [-0.44192573, -0.4980551 ,  0.35986832],
       [-0.6123896 ,  1.3616246 , -0.3762535 ],
       [-0.5483206 ,  0.91513014, -0.10056886],
       [-0.49538013, -1.2710712 ,  1.1525759 ]], dtype=float32)>

In [24]:
tf.random.shuffle(data, seed=42)

<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
array([[-0.44192573, -0.4980551 ,  0.35986832],
       [-1.7790617 ,  0.20539697, -0.22468199],
       [-0.6123896 ,  1.3616246 , -0.3762535 ],
       [-0.49538013, -1.2710712 ,  1.1525759 ],
       [-0.5483206 ,  0.91513014, -0.10056886]], dtype=float32)>