# Tensorflow 2.0

What is `TensorFlow`?

`TensorFlow` is an open-source machine learning library for research and production. TensorFlow offers APIs for beginners and experts to develop for desktop, mobile, web, and cloud. See the sections below to get started.

In this notebook we will see how to get started with `TensorFlow 2.0` and what are `tensors` 

### Installation

```bash
python -m pip install tensorflow
```

If you have a CUDA enabled GPU(NVIDIA) you can install the GPU version of TensorFlow using the following command

```bash
python -m pip install tensorflow-gpu
```

Now if you have installed the `TensorFlow` library, let's see how to get started with it.


In [2]:
import warnings

warnings.filterwarnings("ignore")

In [3]:
import tensorflow as tf
print(tf.__version__)

2024-06-22 14:53:01.071387: I external/local_tsl/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-06-22 14:53:01.076043: I external/local_tsl/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-06-22 14:53:01.138569: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-06-22 14:53:02.922451: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


2.16.1


There you go we have `imported tensorflow` and printed the version of the `tensorflow` library.
I'm using `TensorFlow 2.16.1` in this notebook.

### Tensors

A `tensor` is a `generalization` of vectors and matrices to potentially higher dimensions. Internally, TensorFlow represents tensors as n-dimensional arrays of base datatypes.

there many ways to create `tensors` in `tensorflow` but most common ways are using `tf.constant` and `tf.Variable` functions.

### tf.constant

Here is how you can create a `tensor` using `tf.constant` function


In [4]:
scaler = tf.constant(1)
scaler

<tf.Tensor: shape=(), dtype=int32, numpy=1>

here, we have created a `tensor` that contains a numpy value `1` and the datatype of the tensor is `int32`.

We did it by passing the value `1` to the `tf.constant` function.

We have a tensor in our hand.

Now you might think why does I named the tensor as `scaler` because the tensor we created is a `scaler` tensor.

> A `scaler` value is something that has only magnitude and no direction.

it's like a `0-D` array.

Now how do you know the dimansion of the tensor?

In [5]:
scaler.ndim

0

Here you go. You can just use the `variable_name.ndim` to get the dimension of the tensor.

Now, let's see how to create a `tensor` with `1` dimension.

In [6]:
vector = tf.constant([1, 2, 3])

vector

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

And we have created a `1-D` tensor. We just pass a `list` of values or a `numpy array` to the `tf.constant` function.

And you can see that the tensor is containing a `numpy array` of values `[1, 2, 3]` and the datatype of the tensor is `int32`.

Now we can see the dimansions.

In [7]:
vector.ndim

1

and you see that the tensor is a `1-D` tensor.

> I named the variable as `vector` because a `1-D` tensor is called a `vector`.

And we can keep going. So let's try top make a `2-D` tensor and also a `3-D` tensor.

In [8]:
matrix = tf.constant([
    [1, 2],
    [3, 4]
])

In [9]:
matrix.ndim

2

AAAND we made a `2-D` tensor. We just passed a `list of lists` to the `tf.constant` function. Now we see the shape of the tensor.

In [10]:
matrix.shape

TensorShape([2, 2])

it's a 2 by 2 tensor. Simply it's a `2-D` array  that is having `2` rows and `2` columns. Same Way we can make a `list of lists of lists` to make a `3-D` tensor.

In [11]:
n_dimantional_matrix = tf.constant([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
])

In [12]:
n_dimantional_matrix

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)>

Ther you go, we have created a `3-D` tensor. We just passed a `list of lists of lists` to the `tf.constant` function. Now we see the shape of the tensor.

So, we have created `scaler`, `vector`, `matrix`, and `3-D` tensor using the `tf.constant` function. And i think you can see a pattern here. A tensor is a `n-D` array of values just like a `numpy` array ot python lists. But It has some extra features that we will see as we progress through this notebook.

Now let's see how to create a `tensor` using the `tf.Variable` function.

### tf.Variable

In [13]:
variable = tf.Variable([10, 7])
variable

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>

`tf.variable` and `tf.constant` are almost the same.

- They are tensors.
- They many methods that are similar.

But there is a huge difference between them.

- `tf.constant` is immutable. Once you create a `tf.constant` you can't change the values of the tensor.
- `tf.variable` is mutable. You can change the values of the tensor.

I'll make two tensors one with `tf.constant` and one with `tf.variable` and I'll show you the difference.


In [14]:
constant_tensor = tf.constant([10, 7])
changeable_tensor = tf.Variable([10, 7])
constant_tensor, changeable_tensor

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>)

As you can see they are almost the same Now let's try to change the value of the `tf.variable` tensor.

In [16]:
changeable_tensor[0] = 7

TypeError: 'ResourceVariable' object does not support item assignment

Also for the `tf.constant` tensor.

In [17]:
constant_tensor[0] = 7

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

Both of these will give you an error that you can't change the values of both `tf.constant` and `tf.variable` tensors.

But as i said before you can change the values of the `tf.variable` tensor.

> you change the value of a `tf.variable` tensor using the `assign` method.

In [19]:
changeable_tensor[0].assign(102)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([102,   7], dtype=int32)>

and there you go. We have changed the value of the `tf.variable` tensor.But there is no way to change the value of a `tf.constant` tensor or any function that can do that.

In [20]:
constant_tensor[0].assign(102)

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

As you can see there is a huge error when we start to use the `assign` method on a `tf.constant` tensor.

So, you can do almost everything you can do with a numpy array and much more in a `tensor` in `tensorflow`.