**prerequisite**:

- Basic understanding of numpy and pandas.
- Optional: Overall basic understanding of machine learning.


# Introduction to Tensors with Tensorflow

Helloo everyone, It's been a very long time since I've made any articles and I've been kinda missing the fun of writing articles. So, I'm back with another article series. This article series will be about `Neural Networks` and `TensorFlow`. AS always I'm `Md. Rishat Talukder AKA Itvaya`. let's get this thing started.

- [LinkedIn](https://www.linkedin.com/in/pro-programmer/)
- [YouTube](http://www.youtube.com/@itvaya)
- [gtihub](https://github.com/RishatTalukder/Machine-Learning-Zero-to-Hero)
- [Gmail](talukderrishat2@gmail.com)
- [discord](https://discord.gg/ZB495XggcF)

# Introduction to Tensorflow

What is `TensorFlow`?

`TensorFlow` is an open-source machine learning library for research and production. TensorFlow offers APIs for beginners and experts to develop for desktop, mobile, web, and cloud. See the sections below to get started.

> I like to think of tensorflow as a more powerful version of `numpy`. If you know numpy your work is already 60% done.

In this article we will see how to get started with `TensorFlow` and what are `tensors` ?

## Installation

```bash
python3 -m pip install 'tensorflow[and-cuda]'
```

If you have a Nvidia GPU this should works amazing... And if you don't have a gpu there should be no issue there too.

In [2]:
import warnings

warnings.filterwarnings("ignore")

In [3]:
import tensorflow as tf
print(tf.__version__)

2026-04-23 16:14:13.744653: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


2.20.0


There you go we have `imported tensorflow` and printed the version of the `tensorflow` library.
I'm using `TensorFlow 2.16.1` in this notebook.

### Tensors

A `tensor` is a `generalization` of vectors and matrices to potentially higher dimensions. Internally, TensorFlow represents tensors as n-dimensional arrays of base datatypes.

there many ways to create `tensors` in `tensorflow` but most common ways are using `tf.constant` and `tf.Variable` functions.

### tf.constant

Here is how you can create a `tensor` using `tf.constant` function


In [4]:
scaler = tf.constant(1)
scaler

I0000 00:00:1776939256.006601  336800 gpu_device.cc:2020] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 9566 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3060, pci bus id: 0000:05:00.0, compute capability: 8.6


<tf.Tensor: shape=(), dtype=int32, numpy=1>

here, we have created a `tensor` that contains a numpy value `1` and the datatype of the tensor is `int32`.

if you take a closer look you can see that the shape of the tensor is `()` which means it is a `0-D` tensor. So, it's a scalar.

We have a tensor in our hand.

Now you might think why does I named the tensor as `scaler` because it's a `0-D` tensor AKA a `scaler`.

> A `scaler` value is something that has only magnitude and no direction.

To prove it we can see the dimension of the tensor.

In [5]:
scaler.ndim

0

Here you go. You can just use the `variable_name.ndim` to get the dimension of the tensor.

Now, let's see how to create a `1-D` tensor.

In [6]:
vector = tf.constant([1, 2, 3])

vector

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

And we have created a `1-D` tensor. We just pass a `list` of values or a `numpy array` to the `tf.constant` function.

And you can see that the tensor is containing a `numpy array` of values `[1, 2, 3]` and the datatype of the tensor is `int32` and the shape of the tensor is `(3,)` which means it is a `1-D` tensor.

Now we can see the dimansions.

In [7]:
vector.ndim

1

and you see that the tensor is a `1-D` tensor.

> A `vector` is a 1-D array of values.

And we can keep going. So let's try top make a `2-D` tensor and also a `3-D` tensor.

In [8]:
matrix = tf.constant([
    [1, 2],
    [3, 4]
])

In [9]:
matrix.ndim

2

AAAND we made a `2-D` tensor. We just passed a `list of lists` to the `tf.constant` function. Now we see the shape of the tensor.

In [10]:
matrix.shape

TensorShape([2, 2])

it's a 2 by 2 tensor. Simply it's a `2-D` array of values is refered to as a `matrix`.

In [11]:
n_dimantional_matrix = tf.constant([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
])

In [12]:
n_dimantional_matrix

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)>

Ther you go, we have created a `3-D` tensor. We just passed a `list of lists of lists` to the `tf.constant` function. Now we see the shape of the tensor.

So, we have created `scaler`, `vector`, `matrix`, and `3-D` or anything greater then that is called a `tensor` in general.

> 0-d array is called a `scaler`. 1-d array is called a `vector`. 2-d array is called a `matrix`. n-d array is called a `tensor`.

Now let's see how to create a `tensor` using the `tf.Variable` function.

`tf.constant` has many more methods and attributes that we can use and also we can pass different arguments to set the data type of the tensor, shape of the tensor, etc.

In [13]:
tf.constant([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]], dtype=tf.float16)

<tf.Tensor: shape=(2, 2, 3), dtype=float16, numpy=
array([[[ 1.,  2.,  3.],
        [ 4.,  5.,  6.]],

       [[ 7.,  8.,  9.],
        [10., 11., 12.]]], dtype=float16)>

YOu should check out the official documentations for [constant](https://www.tensorflow.org/api_docs/python/tf/constant)

Although `tf.constant` is great for creating a `tensor` but it's not the only way and this constant tensor is immutable. Once you create a constant tensor you can't change the values of the tensor.



### tf.Variable

In [14]:
variable = tf.Variable([10, 7])
variable

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>

`tf.variable` and `tf.constant` are almost the same.

- They are tensors.
- They many methods that are similar.

But there is a huge difference between them.

- `tf.constant` is immutable. Once you create a `tf.constant` you can't change the values of the tensor.
- `tf.variable` is mutable. You can change the values of the tensor.

I'll make two tensors one with `tf.constant` and one with `tf.variable` and I'll show you the difference.


In [15]:
constant_tensor = tf.constant([10, 7])
changeable_tensor = tf.Variable([10, 7])
constant_tensor, changeable_tensor

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>)

As you can see they are almost the same Now let's try to change the value of the `tf.variable` tensor.

In [16]:
changeable_tensor[0] = 7

TypeError: 'ResourceVariable' object does not support item assignment

Also for the `tf.constant` tensor.

In [ ]:
constant_tensor[0] = 7

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

Both of these will give you an error that you can't change the values of both `tf.constant` and `tf.variable` tensors.

But as i said before you can change the values of the `tf.variable` tensor.

> you change the value of a `tf.variable` tensor using the `assign` method.

In [ ]:
changeable_tensor[0].assign(102)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([102,   7], dtype=int32)>

and there you go. We have changed the value of the `tf.variable` tensor.But there is no way to change the value of a `tf.constant` tensor or any function that can do that.

In [ ]:
constant_tensor[0].assign(102)

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

As you can see there is a huge error when we start to use the `assign` method on a `tf.constant` tensor.

So, you can do almost everything you can do with a numpy array and much more in a `tensor` in `tensorflow`.