# Random Tensors

`Tensors` are basic building blocks in `tensorflow`. But sometimes we need to create random tensors. In this notebook, we will see how to create random tensors in `tensorflow`.

So, how do we create random tensors in `tensorflow`?

In [1]:
import tensorflow as tf

2024-06-22 22:07:19.361873: I external/local_tsl/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-06-22 22:07:19.365460: I external/local_tsl/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-06-22 22:07:19.429910: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-06-22 22:07:20.971995: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


In [11]:
tf.random.Generator.from_seed(42)

In [16]:

random_1 = tf.random.Generator.from_seed(42).normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42).normal(shape=(3,2))

In [17]:
random_1,random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>)