# Suffling a tensor

Suppose, you have a tensor where the 100 elements are pictures of cats and last 50 elements are pictures of dogs. Your deep learning model is learning to classify cats for the first 100 elements and dogs for the last 50 elements. This can be a problem because the model can learn to classify cats for the first 100 elements and dogs for the last 50 elements. To avoid this, you can shuffle the tensor.

In [5]:
import warnings
import tensorflow as tf

warnings.filterwarnings("ignore")

In [6]:
dummy_tenosr = tf.constant([[1, 2], [3, 4], [5, 6]])
dummy_tenosr

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [7]:
tf.random.shuffle(dummy_tenosr)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[5, 6],
       [3, 4],
       [1, 2]], dtype=int32)>